name: Mypy type hint checks

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Micromamba env
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: TEST
        create-args: >-
          python=${{ matrix.python-version }}
          --file requirements.txt
          --file requirements-dev.txt
        # conda-forge is the default channel now and does not need to be specified

    - name: Create env
      shell: bash -l {0}
      run: |
        python -m pip install -e . --no-deps --force-reinstall

    - name: Selenium tests
      shell: bash -l {0}
      run: |
        mypy folium
